# Generated by Django 5.0.3 on 2024-03-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.ImageField(upload_to='check/')),
                ('back', models.ImageField(upload_to='check/')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='mainApp.transactions')),
            ],
        ),
    ]
