# Generated by Django 5.0.3 on 2024-04-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_checktransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
