# Generated by Django 5.0.3 on 2024-04-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_transactions_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
