# Generated by Django 5.0.3 on 2024-05-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_accounts_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_opened',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
