# Generated by Django 5.0.3 on 2024-05-02 16:22

import mainApp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_accounts_newid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='source',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='newid',
            field=models.IntegerField(default=mainApp.models.Accounts.generateID, primary_key=True, serialize=False),
        ),
    ]
