# Generated by Django 5.0.3 on 2024-05-05 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_users_date_opened'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.UUIDField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date_opened', models.DateField()),
                ('account_type', models.CharField(max_length=50)),
                ('date_deleted', models.DateField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
