# Generated by Django 5.0.3 on 2024-05-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_remove_transactions_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='id',
        ),
    ]
