# Generated by Django 5.0.3 on 2024-05-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_remove_accounts_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='newid',
            new_name='id',
        ),
    ]
