# Generated by Django 5.0.3 on 2024-05-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_transactions_destination_transactions_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktransactions',
            name='memo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checktransactions',
            name='recipient_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checktransactions',
            name='sender_info',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checktransactions',
            name='spelled_amount',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
