# Generated by Django 5.0.3 on 2024-05-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_checktransactions_memo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_opened',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
