# Generated by Django 5.0.3 on 2024-05-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_accounts_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
