# Generated by Django 5.0.3 on 2024-05-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_accounts_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='date_deleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
