# Generated by Django 5.0.3 on 2024-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_transactions_error_alter_users_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
