# Generated by Django 5.0.3 on 2024-05-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_alter_transactions_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
